name: lemaker-guitar-kernel
version: 3.10.94
summary: A lemaker guitar kernel built from source
description: This is reference kernel from lemaker branch linux-3.10.y-snappy
type: kernel
architectures: [ armhf ]

parts:
  kernel:
    plugin: kernel
    source: .
    source-branch: linux-3.10.y-snappy
    source-type: git
    kdefconfig: [snappy-atm705a_s500_defconfig]
    kconfigs:
      - CONFIG_LOCALVERSION="-snappy_v3.10"
      - CONFIG_DEBUG_INFO=n
      - CONFIG_SQUASHFS=m
    kernel-initrd-modules:
      - squashfs
    kernel-image-target: zImage
    kernel-device-trees:
      - lemaker_guitar_bbb
    build-packages: [bc, kmod, cpio]
